Repository FEDarling/weekly-tracker, pull requests merged in 2022-01, with the labels that each got.

#2 feature: JavaScript Weekly #570 添加三元运算符翻译
  JavaScript_Weekly/570/index.md
  JavaScript_Weekly/570/ternary.md
  README.md
Labels: translate

#7 添加git自动化脚本
  .gitlgnore
  pull.sh
  push.sh
Labels: 自动化

#22 新增webRTC文章
  Mobile_Dev_Weekly/382/index.md
  Mobile_Dev_Weekly/382/webrtc.md
  README.md
Labels: feature

#25 新增JS引擎原型
  JavaScript_Weekly/399/index.md
  JavaScript_Weekly/399/js_engine_optimizing_prototype.md
  JavaScript_Weekly/399/js_engine_shape_and_inline_caches.md
  README.md
Labels: feature

#28 自动化pull和push
  .gitIgnore
  .gitlgnore
  autoCommit.js
  package-lock.json
  package.json
  pull.sh
  push.sh
Labels: 自动化

#29 自动化兜底测试
  README.md
Labels: 自动化

#68 修改预览页面logo错误和readme错别字
  README.md
  weeklys/.vuepress/config.js
  weeklys/css_weekly/485/README.md
  weeklys/css_weekly/485/dynamic_color_manipulation_with_css_relative_colors.md
  weeklys/css_weekly/486/README.md
  weeklys/javascript_weekly/571/README.md
  weeklys/javascript_weekly/571/flatMap.md
  weeklys/javascript_weekly/571/fuite.md
Labels: style

#69 修改文字错误
  .github/ISSUE_TEMPLATE/weekly-issue.md
  README.md
Labels: fix

#71 添加 CSS Weekly #486精选文章，并解决 CSS Weekly#485 文章遗漏Bug
  weeklys/css_weekly/485/breaking_out_of_the_box.md
  weeklys/css_weekly/485/building_a_toast_component.md
  weeklys/css_weekly/485/combat_css_blockage_with_this_one_weird_little_trick.md
  weeklys/css_weekly/485/details_and_summary.md
  weeklys/css_weekly/485/ffflux.md
  weeklys/css_weekly/485/standardizing_focus_styles_with_css_custom_properties.md
  weeklys/css_weekly/486/README.md
  weeklys/css_weekly/486/SVGcode.md
  weeklys/css_weekly/486/compat_2021_holiday_update.md
  weeklys/css_weekly/486/css_me_not.md
  weeklys/css_weekly/486/has_selector.md
  weeklys/css_weekly/486/preference_queries.md
  weeklys/css_weekly/486/smoothly_reverting_css_animations.md
  weeklys/css_weekly/486/tailwind_and_the_femininity_of_CSS.md
Labels: 校对中

#83 添加新的周刊
  weeklys/frontend_focus/524/README.md
  weeklys/javascript_weekly/573/README.md
  weeklys/node_weekly/421/README.md
Labels: 待格式化
