Repository FEDarling/weekly-tracker, pull requests merged in 2022-02, with the labels that each got.

#102 fix: 修改链接错误和格式问题
  weeklys/.vuepress/config.js
  weeklys/javascript_weekly/571/flatMap.md
Labels: fix

#100 添加新的周刊
  .github/workflows/get-new-weekly.yml
  weeklys/frontend_focus/525/README.md
  weeklys/javascript_weekly/574/README.md
  weeklys/node_weekly/422/README.md
  weeklys/react_status/273/README.md
Labels: 待格式化

#104 添加新的周刊
  weeklys/frontend_focus/527/README.md
Labels: 待格式化

#110 添加新的周刊
  weeklys/javascript_weekly/575/README.md
Labels: 待格式化

#124 添加新的周刊
  weeklys/frontend_focus/528/README.md
  weeklys/node_weekly/424/README.md
  weeklys/react_status/275/README.md
Labels: 待格式化

#171 添加新的周刊
  .github/workflows/get-new-weekly.yml
  weeklys/frontend_focus/529/README.md
  weeklys/javascript_weekly/576/README.md
  weeklys/node_weekly/425/README.md
  weeklys/react_status/276/README.md
Labels: 待格式化

#139 feat: JavaScript Weekly #571 补充空白文
  weeklys/javascript_weekly/571/Is_It_Time_for_the_JavaScript_Temporal_API.md
Labels: 校对中

#188 添加新的周刊
  weeklys/css_weekly/493/README.md
  weeklys/frontend_focus/530/README.md
  weeklys/javascript_weekly/578/README.md
  weeklys/node_weekly/426/README.md
  weeklys/react_status/277/README.md
Labels: 待格式化
